# Generated by Codex for emergency safeguarding fields

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0040_remove_external_user_roles"),
    ]

    operations = [
        migrations.AddField(model_name="alert", name="is_emergency", field=models.BooleanField(default=False)),
        migrations.AddField(model_name="alert", name="is_immediate_danger", field=models.BooleanField(default=False)),
        migrations.AddField(model_name="alert", name="priority_level", field=models.CharField(default="Normal", max_length=20)),
        migrations.AddField(model_name="alert", name="emergency_classification", field=models.CharField(default="NON_EMERGENCY", max_length=40)),
        migrations.AddField(model_name="alert", name="child_moved_to_safety", field=models.CharField(blank=True, max_length=40)),
        migrations.AddField(model_name="intake", name="is_emergency", field=models.BooleanField(default=False)),
        migrations.AddField(model_name="intake", name="is_immediate_danger", field=models.BooleanField(default=False)),
        migrations.AddField(model_name="intake", name="priority_level", field=models.CharField(default="Normal", max_length=20)),
        migrations.AddField(model_name="intake", name="emergency_classification", field=models.CharField(default="NON_EMERGENCY", max_length=40)),
        migrations.AddField(model_name="intake", name="child_moved_to_safety", field=models.CharField(blank=True, max_length=40)),
        migrations.AddField(model_name="intake", name="emergency_change_reason", field=models.TextField(blank=True)),
    ]
