# Generated by Codex after simplifying emergency intake fields.

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0041_emergency_safeguarding_flags"),
    ]

    operations = [
        migrations.RunSQL(
            sql="""
                ALTER TABLE core_alert
                    DROP COLUMN IF EXISTS immediate_action_plan,
                    DROP COLUMN IF EXISTS immediate_action_at,
                    DROP COLUMN IF EXISTS immediate_action_responsible,
                    DROP COLUMN IF EXISTS immediate_action_status,
                    DROP COLUMN IF EXISTS supervisor_notified,
                    DROP COLUMN IF EXISTS supervisor_notification_at,
                    DROP COLUMN IF EXISTS supervisor_notified_no_reason,
                    DROP COLUMN IF EXISTS referral_authority_contacted;

                ALTER TABLE core_intake
                    DROP COLUMN IF EXISTS immediate_action_at,
                    DROP COLUMN IF EXISTS immediate_action_responsible,
                    DROP COLUMN IF EXISTS immediate_action_status,
                    DROP COLUMN IF EXISTS supervisor_notified,
                    DROP COLUMN IF EXISTS supervisor_notification_at,
                    DROP COLUMN IF EXISTS supervisor_notified_no_reason,
                    DROP COLUMN IF EXISTS referral_authority_contacted;
            """,
            reverse_sql=migrations.RunSQL.noop,
        ),
    ]
