# Generated by Codex for system safeguarding classification.

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [("core", "0055_remove_retired_case_fields")]

    operations = [
        migrations.AddField(model_name="intake", name="safeguarding_classification", field=models.CharField(default="NORMAL", max_length=30)),
        migrations.AddField(model_name="intake", name="classification_source", field=models.CharField(default="SYSTEM", max_length=20)),
        migrations.AddField(model_name="intake", name="classification_rule_version", field=models.CharField(default="CASE-TYPE-RULES-1.0", max_length=40)),
        migrations.AddField(model_name="intake", name="classification_trigger_codes", field=models.JSONField(blank=True, default=list)),
        migrations.AddField(model_name="intake", name="classification_calculated_at", field=models.DateTimeField(blank=True, null=True)),
    ]
